set(PROJECT_TITLE "viewsvg")

if (DEFINED VERSION_TAG)
    set(PROJECT_VERSION "${VERSION_TAG}")
elseif (DEFINED ENV{VERSION_TAG})
    set(PROJECT_VERSION "$ENV{VERSION_TAG}")
else ()
    message(FATAL "VERSION_TAG not set")
endif ()

set(PROJECT_NAME_QML ${PROJECT_TITLE}_qml)

file(GLOB_RECURSE SOURCES_CPP src/*.cpp)
file(GLOB_RECURSE SOURCES_HPP src/*.hpp)
file(
    GLOB_RECURSE SOURCES_QML
    RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
    *.qml
)

set(RESVG_ROOT_PATH "${CMAKE_SOURCE_DIR}/../..")
set(RESVG_LIB_PATH "${RESVG_ROOT_PATH}/target/release")

add_definitions(-DVERSION_TAG="${PROJECT_VERSION}")

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
